[2025-10-24T11:03:57.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-24T11:03:57.651+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecar_etl_pipeline.extract_raw_data manual__2025-10-24T11:00:55.729105+00:00 [queued]>
[2025-10-24T11:03:57.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecar_etl_pipeline.extract_raw_data manual__2025-10-24T11:00:55.729105+00:00 [queued]>
[2025-10-24T11:03:57.657+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-24T11:03:57.664+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-10-24 11:00:55.729105+00:00
[2025-10-24T11:03:57.673+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecar_etl_pipeline', 'extract_raw_data', 'manual__2025-10-24T11:00:55.729105+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ecar_dag.py', '--cfg-path', '/tmp/tmp6t8bvh8a']
[2025-10-24T11:03:57.676+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask extract_raw_data
[2025-10-24T11:03:57.676+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-24T11:03:57.678+0000] {standard_task_runner.py:63} INFO - Started process 175 to run task
[2025-10-24T11:03:57.704+0000] {task_command.py:426} INFO - Running <TaskInstance: ecar_etl_pipeline.extract_raw_data manual__2025-10-24T11:00:55.729105+00:00 [running]> on host 2198fce1af6c
[2025-10-24T11:03:57.750+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='ecar_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-24T11:00:55.729105+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-24T11:00:55.729105+00:00'
[2025-10-24T11:03:57.751+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-24T11:03:57.762+0000] {ecar_dag.py:24} INFO - Running script: /Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py
[2025-10-24T11:03:57.810+0000] {ecar_dag.py:27} ERROR - python: can't open file '/Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py': [Errno 2] No such file or directory

[2025-10-24T11:03:57.810+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-24T11:03:57.811+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ecar_dag.py", line 28, in run_script
    raise RuntimeError(f"Script failed: {script_path}")
RuntimeError: Script failed: /Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py
[2025-10-24T11:03:57.828+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecar_etl_pipeline, task_id=extract_raw_data, run_id=manual__2025-10-24T11:00:55.729105+00:00, execution_date=20251024T110055, start_date=20251024T110357, end_date=20251024T110357
[2025-10-24T11:03:57.836+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task extract_raw_data (Script failed: /Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py; 175)
[2025-10-24T11:03:57.868+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-24T11:03:57.887+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-24T11:03:57.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
