[2025-10-24T11:00:56.835+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-24T11:00:56.854+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecar_etl_pipeline.extract_raw_data manual__2025-10-24T11:00:55.729105+00:00 [queued]>
[2025-10-24T11:00:56.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecar_etl_pipeline.extract_raw_data manual__2025-10-24T11:00:55.729105+00:00 [queued]>
[2025-10-24T11:00:56.857+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-24T11:00:56.872+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-10-24 11:00:55.729105+00:00
[2025-10-24T11:00:56.880+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-24T11:00:56.881+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2025-10-24T11:00:56.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecar_etl_pipeline', 'extract_raw_data', 'manual__2025-10-24T11:00:55.729105+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ecar_dag.py', '--cfg-path', '/tmp/tmpdtdwoe00']
[2025-10-24T11:00:56.888+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_raw_data
[2025-10-24T11:00:56.933+0000] {task_command.py:426} INFO - Running <TaskInstance: ecar_etl_pipeline.extract_raw_data manual__2025-10-24T11:00:55.729105+00:00 [running]> on host 2198fce1af6c
[2025-10-24T11:00:56.979+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='ecar_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-24T11:00:55.729105+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-24T11:00:55.729105+00:00'
[2025-10-24T11:00:56.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-24T11:00:56.999+0000] {ecar_dag.py:24} INFO - Running script: /Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py
[2025-10-24T11:00:57.050+0000] {ecar_dag.py:27} ERROR - python: can't open file '/Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py': [Errno 2] No such file or directory

[2025-10-24T11:00:57.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-24T11:00:57.050+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ecar_dag.py", line 28, in run_script
    raise RuntimeError(f"Script failed: {script_path}")
RuntimeError: Script failed: /Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py
[2025-10-24T11:00:57.061+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecar_etl_pipeline, task_id=extract_raw_data, run_id=manual__2025-10-24T11:00:55.729105+00:00, execution_date=20251024T110055, start_date=20251024T110056, end_date=20251024T110057
[2025-10-24T11:00:57.096+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract_raw_data (Script failed: /Users/kaancakir/data_projects_local/ecar-pipeline/src/extract_ecar.py; 170)
[2025-10-24T11:00:57.105+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-24T11:00:57.115+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-24T11:00:57.116+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
